[versions]
minecraft = "1.20.1"

quilt_loader = "0.19.1"
quilt_mappings = "1.20.1+build.1"
quilted_fabric_api = "7.0.3+0.83.1-1.20.1"
quilt_kotlin_libraries = "2.1.0+kt.1.8.22+flk.1.9.4"

kotlin = "1.8.22"
quilt_loom = "1.2.+"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }

quilt_loader = { module = "org.quiltmc:quilt-loader", version.ref = "quilt_loader" }
quilt_mappings = { module = "org.quiltmc:quilt-mappings", version.ref = "quilt_mappings" }
quilted_fabric_api = { module = "org.quiltmc.quilted-fabric-api:quilted-fabric-api", version.ref = "quilted_fabric_api" }
quilt_kotlin_libraries = { module = "org.quiltmc.quilt-kotlin-libraries:quilt-kotlin-libraries", version.ref = "quilt_kotlin_libraries" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
quilt_loom = { id = "org.quiltmc.loom", version.ref = "quilt_loom" }
